// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewStock struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Volume string   `json:"volume"`
	Reason []string `json:"reason"`
}

type Stock struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Volume string   `json:"volume"`
	Reason []string `json:"reason"`
}
