// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewStock struct {
	Name   string   `json:"name"`
	Volume string   `json:"volume"`
	Reason []string `json:"reason"`
}

type StandardPayload struct {
	Msg  *string     `json:"Msg"`
	Data interface{} `json:"Data"`
}

type StandardResponse struct {
	Code    int              `json:"Code"`
	Payload *StandardPayload `json:"Payload"`
}

type Stock struct {
	Name   string   `json:"name"`
	Volume string   `json:"volume"`
	Reason []string `json:"reason"`
}
